apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-resume-upload
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-resume-upload
  ports:
  - protocol: TCP
    port: {{ .Values.services.resume_upload.port }}
    targetPort: {{ .Values.services.resume_upload.port }}