apiVersion: v2
name: fastapi-backends
description: A Helm chart for Kubernetes to deploy FastAPI backends which consists of applications that require a mysql database.
version: 0.1.3
appVersion: "1.0.1"
