apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-jd-upload
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.services.jd_upload.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-jd-upload
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-jd-upload
    spec:
      containers:
        - name: jd-upload-container
          image: {{ .Values.services.jd_upload.image }}
          imagePullPolicy: {{ .Values.services.jd_upload.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.services.jd_upload.port }}