apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-jd-upload
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-jd-upload
  ports:
  - protocol: TCP
    port: {{ .Values.services.jd_upload.port }} # Service port
    targetPort: {{ .Values.services.jd_upload.port }} # Container port