name: Release Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'

permissions:
  contents: write    
  pages: write      
  id-token: write   

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: setup git config
        run: |
          git config --global user.email "$GITHUB_ACTOR"
          git config --global user.name "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Package and Release
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: "${{ secrets.CR_TOKEN }}"